[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/bacon/CR10_data/comms/klippy.sock

[authorization]
trusted_clients:
    192.168.193.0/24
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/24
    FE80::/10
    ::1/128

    
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz


[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[update_manager mobileraker]
type: git_repo
path: /home/bacon/mobileraker_companion
origin: https://github.com/Clon1998/mobileraker_companion.git
primary_branch:main
managed_services: mobileraker
env: /home/bacon/mobileraker-env/bin/python
requirements: scripts/mobileraker-requirements.txt
install_script: scripts/install.sh
is_system_service: False
#[spoolman]
#server: http://192.168.0.49:7912


#[update_manager Spoolman]
#type: zip
#channel: stable
#repo: Donkie/Spoolman
#path: /home/bacon/Spoolman
#virtualenv: .venv
#requirements: requirements.txt
#persistent_files:
#  .venv
#  .env
#managed_services: Spoolman


[include octoeverywhere-system.cfg]

[simplyprint]

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[timelapse]
        output_path: ~/CR10_data/timelapse/
        frame_path: /tmp/timelapse/CR10

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[spoolman]
server: https://spool.babuca.net
sync_rate:60